name: scene_of_crime_officer_monitor
version: 0.1.0
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  crypto: ^3.0.3
  path: ^1.9.0
  sqlite3: ^2.4.6
  yaml: ^3.1.2
  convert: ^3.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
